const types = {
  FETCH_LOCATIONS: 'FETCH_LOCATIONS',
  FETCH_CURR_WEATHER: 'FETCH_CURR_WEATHER',
  SELECT_LOCATION: 'SELECT_LOCATION',
  FETCH_DAILY_FORECAST: 'FETCH_DAILY_FORECAST',
  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
  REMOVE_FROM_FAVORITES: 'REMOOVE_FROM_FAVORITES',
  SET_FAVORITES: 'SET_FAVORITES',
  FETCH_CURRENT_LOCATION: 'FETCH_CURRENT_LOCATION'
};

export default types;
